update

diff --git a/.github/workflows/mlops.yaml b/.github/workflows/mlops.yaml
--- a/.github/workflows/mlops.yaml
+++ b/.github/workflows/mlops.yaml
@@ -12,18 +12,21 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      # Authentification à GCP
-      - name: Login to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
-          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
+      # Définir la clé de service en tant que fichier
+      - name: Setup Google Cloud credentials
+        run: |
+          # Copier le fichier service-account-key.json depuis le repo
+          cp service-account-key.json /tmp/service-account-key.json
+          # Exporter la variable d'environnement pour les commandes GCP
+          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json" >> $GITHUB_ENV
 
       - name: Configure gcloud
         run: gcloud config set project modern-bond-303506
 
       # Vérifier les permissions sur le bucket
       - name: Check GCS Bucket Access
-        run: gsutil ls gs://sportify_classifier || echo "Bucket access failed, ensure credentials and permissions are correct"
+        run: |
+          gsutil ls gs://sportify_classifier || echo "Bucket access failed, ensure credentials and permissions are correct"
 
       # Construire l'image Docker et la pousser sur GCR
       - name: Build and push Docker image
